### ISSUE TITLE
Peer:2:Peer Code Review

### ISSUE THREAD

**Issue by rammazzoti2000** [vzdrizhni/Tic-tac-toe_JS#3]
Please leave some comments

**Comment by nyatindopatrick** [comment]
Nice logic and UI over there 👍.
For a user to know what's wrong I think you can add alert to display the errors also. I tried this and it works like a charm!
` alert('Cannot assign a new value to a populated cell.')
  throw new Error('Cannot assign a new value to a populated cell.');`

Otherwise Good work!

**Comment by rammazzoti2000** [comment]
@nyatindopatrick That is great, didn't know that, will use it right away :smile: 
Update:
It worked except it has to be on a new line:
```
alert('Cannot assign a new value to a populated cell.');
throw new Error('Cannot assign a new value to a populated cell.');
```
You can [check it here](https://raw.githack.com/vzdrizhni/Tic-tac-toe_JS/V1.0/index.html) :point_left:

**Comment by nyatindopatrick** [comment]
> @nyatindopatrick That is great, didn't know that, will use it right away 
> Update:
> It worked except it has to be on a new line:
> 
> ```
> alert('Cannot assign a new value to a populated cell.');
> throw new Error('Cannot assign a new value to a populated cell.');
> ```
> 
i did it in newline but github comment messed my formatting😃
